/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aofm_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author REUBEN
 */
public class StatActivity extends javax.swing.JFrame {
    
    /**
     * Creates new form StatActivity
     */
    public StatActivity() {
        initComponents();
        
    }

    public StatActivity(String applicationTitle, String chartTitle) {
        super(applicationTitle);
        initComponents();
        JFreeChart barChart = ChartFactory.createBarChart( chartTitle, "Weeks("+StatDataActivity.statVal+")", "Attendance", createDataset(),
                PlotOrientation.VERTICAL, true, true, false );
        ChartPanel chartPanel = new ChartPanel( barChart ); 
        CategoryPlot categoryPlot = barChart.getCategoryPlot();
        BarRenderer br = (BarRenderer) categoryPlot.getRenderer();
        br.setMaximumBarWidth(.05);
        //br.setItemMargin(0);
        chartPanel.setPreferredSize(new java.awt.Dimension( 560 , 367 ) );
        setContentPane( chartPanel );
        setLocationRelativeTo(null);
    }
    
     private CategoryDataset createDataset(){
        final String cell = "CELL MEETING";
        final String sun = "SUNDAY SERVICE";
        
        final DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try{
                    String userName  = "root";
                    String passWord = "";
                    String url = "jdbc:mysql://localhost:3306/aofm_db";
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = (Connection) DriverManager.getConnection(url,userName,passWord);
                    PreparedStatement pstmt = con.prepareStatement("select * from cell_attendance where date like \'%"+StatDataActivity.statVal+"%\'");
                    ResultSet rset = pstmt.executeQuery();
                    int x = 1;
                    while(rset.next()){
                        dataset.addValue( rset.getInt("number") , cell , String.valueOf(x) );
                        x++;
                    }
                    
                    pstmt = con.prepareStatement("select * from sun_attendance where date like \'%"+StatDataActivity.statVal+"%\'");
                    rset = pstmt.executeQuery();
                    int y = 1;
                    while(rset.next()){
                        dataset.addValue( rset.getInt("number") , sun , String.valueOf(y) );
                        y++;
                    }
                    
                }catch(Exception e){}       
        
        
        return dataset;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new StatActivity().setVisible(true);
                
                StatActivity sa = new StatActivity("AOFM Growth Statistics" , "Annual Micro-Church Growth ");
                sa.pack();
                RefineryUtilities.centerFrameOnScreen(sa);
                sa.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
